In [1]:
from tools.rec_sys import Recommender

recommender = Recommender()

[nltk_data] Downloading package stopwords to /Users/isel-
[nltk_data]     har/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Non-personalized approaches

Top-250 tracks

In [17]:
df = recommender.top_250_tracks()
df.head(5)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,artist,title,play_count
0,Dwight Yoakam,You're The One,726885.0
1,Björk,Undo,648239.0
2,Kings Of Leon,Revelry,527893.0
3,Harmonia,Sehr kosmisch,425463.0
4,Barry Tuckwell/Academy of St Martin-in-the-Fie...,Horn Concerto No. 4 in E flat K495: II. Romanc...,389880.0

In [18]:
df.tail(5)

                           artist                        title  play_count
245              Triple Six Mafia    Now I'm High_ Really High     35253.0
246    The Red Jumpsuit Apparatus    Face Down (Album Version)     35245.0
247                   Linkin Park   New Divide (Album Version)     35191.0
248      Selena Gomez & The Scene                    Naturally     35074.0
249  Creedence Clearwater Revival  Have You Ever Seen The Rain     34831.0

Top-100 tracks by genre

In [19]:
df = recommender.top_100_tracks_by_genre('Rock')
df.head(5)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

          artist          title  play_count
0          Björk           Undo    648239.0
1  Kings Of Leon        Revelry    527893.0
2       Harmonia  Sehr kosmisch    425463.0
3    OneRepublic        Secrets    292642.0
4       Tub Ring        Invalid    268353.0

In [20]:
df.tail(5)

          artist              title  play_count
95        Metric    Gold Guns Girls     28148.0
96     Pearl Jam       Encore Break     27579.0
97      Daughtry        No Surprise     27187.0
98  Eric Clapton    Tears In Heaven     26999.0
99     Nick Lowe  All Men Are Liars     26683.0

In [21]:
df = recommender.top_100_tracks_by_genre('Rap')
df.head(5)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

            artist         title  play_count
0  Alliance Ethnik    Représente    241669.0
1     Beastie Boys   The Maestro     72381.0
2           Eminem    Without Me     63918.0
3  Black Eyed Peas       Imma Be     62438.0
4         Kid Cudi  Up Up & Away     59810.0

In [22]:
df.tail(5)

                  artist            title  play_count
95               Shwayze          Buzzin'      7384.0
96               Orishas          El Kilo      7324.0
97            Snoop Dogg  Sexual Eruption      7171.0
98  Bone Thugs-N-Harmony   Tha Crossroads      7124.0
99               Orishas           Habana      6998.0

In [23]:
df = recommender.top_100_tracks_by_genre('Electronic')
df.head(5)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,artist,title,play_count
0,Southside Spinners,Luvstruck,84225.0
1,The Black Keys,Tighten Up,81179.0
2,Deadmau5,Ghosts 'n' Stuff (Original Instrumental Mix),63951.0
3,Daft Punk,Harder Better Faster Stronger,63170.0
4,Clara Hill,Clara meets Slope - Hard To Say,58887.0

In [24]:
df.tail(5)

,artist,title,play_count
95,Nicolette,No Government,9541.0
96,Two Door Cinema Club,Eat That Up_ It's Good For You,9524.0
97,Moby,Why Does My Heart Feel So Bad? (2006 Digital R...,9491.0
98,Death In Vegas,Girls,9490.0
99,Johan Gielen,Flash,9431.0

Content-based approach
Collections

Baseline: using keyword and the number of its occurrences in a song with a threshold

Wrong keyword given

In [25]:
df = recommender.collections(theme='math', approach='baseline')
df.head(10)

theme : math
Incorrect given keyword 'math'

Empty DataFrame
Columns: []
Index: []

In [26]:
df = recommender.collections(theme='love', approach='baseline')
df

theme : love
(4320, 3)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,artist,title,play_count
0,Bill Withers,Make Love To Your Mind,146978.0
1,John Mayer,Half Of My Heart,65966.0
2,Crystal Castles,Not In Love,24681.0
3,Modern Lovers,Modern world,20584.0
4,The B-52's,Love Shack,20226.0
5,Transvision Vamp,I Want Your Love,19988.0
6,Jim Sturgess,All My Loving,16398.0
7,Sense Field,Am I A Fool,16167.0
8,Céline Dion,My Heart Will Go On,16133.0
9,Air,Playground Love,15987.0
10,Neil Young,Love And Only Love (1991 Live LP Version),15625.0
11,Coldplay,Politik,14000.0
12,OutKast,The Way You Move,11923.0
13,Metric,Stadium Love,11395.0
14,Elton John / Kiki Dee,Don't Go Breaking My Heart,11196.0
15,Eric Church,Love Your Love The Most,10738.0
16,Foals,Big Big Love (Fig .2),9844.0
17,Wilson Pickett,I'm In Love (Single/LP Version),9713.0
18,Mel & Kim,F L M,9632.0
19,Radney Foster,Drunk On Love,8871.0
20,Lostprophets,Rooftops,8804.0
21,Beyoncé,Dangerously In Love,8336.0
22,Scouting for Girls,She's So Lovely,8077.0
23,Florence + The Machine,Hardest Of Hearts,8017.0
24,Cassie,Kiss Me (Album Version),7524.0
25,Tears For Fears,Sowing The Seeds Of Love,6996.0
26,U2,Window In The Skies,6975.0
27,Tonic,If You Could Only See,6853.0
28,Robert Palmer,Addicted To Love,6835.0
29,Angels and Airwaves,Breathe,6834.0
30,Bjork,Bachelorette (Family Tree Version),6787.0
31,Razorlight,Wire To Wire,6459.0
32,Regina Spektor,Another Town,6098.0
33,Charly García,Asesíname,5869.0
34,Randy Crawford,One Day I'll Fly Away,5554.0
35,Amy Winehouse,Cupid,5500.0
36,MGMT,It's Working,5435.0
37,Simian Mobile Disco,Love,5389.0
38,Stevie Wonder,Knocks Me Off My Feet,5384.0
39,Feist,The Limit To Your Love,5179.0
40,Massive Attack,Girl I Love You,5122.0
41,Mason Jennings,Something About Your Love,5015.0
42,Clay Walker,What's It To You (Album Version),4712.0
43,Tenth Avenue North,Love Is Here,4700.0
44,José González,Love Will tear Us Apart,4583.0
45,Sara Bareilles,Winter Song,4500.0
46,Sia,Buttons,4437.0
47,Pete Townshend,Let My Love Open The Door,4410.0
48,Edward Sharpe & The Magnetic Zeros,Simplest Love,4326.0
49,Amy Winehouse,Love Is A Losing Game,4231.0

Word2Vec: same approach but look for several similar tokens using word2vec

In [30]:
df = recommender.collections(theme='happiness', approach='word2vec')
print(df.shape)
df.head(10)

theme : happiness
(134, 3)
data frame saved as data/happiness_data.csv for training

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

(50, 3)

,artist,title,play_count
0,Bad Company,Cross Country Boy,1606.0
1,Josh Turner,Your Smile,1036.0
2,Soundgarden,Head Down,983.0
3,Michael Bublé,Smile (Live),790.0
4,Au Revoir Simone,Knight of Wands,590.0
5,Charlie Winston,I Love Your Smile,584.0
6,Michael Jackson,Smile,573.0
7,Devendra Banhart,Can't Help But Smiling (Album Version),537.0
8,David Crowder*Band,You Are My Joy (Everything Glorious Album Vers...,527.0
9,Kate Bush,Bertie,459.0

Classification: label data and predict theme using trained classifier for other part of the dataset

In [31]:
df = recommender.collections(theme='war', process=True, approach='classification')
print(df.shape)
df.head(10)

theme : war
data processing...
preprocessed train/test split and classes saved at data/
classifier accuracy reached on test set: 0.9849397590361446

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

(50, 3)

                     artist                title  play_count
0                 The Kills   Love Is A Deserter      3601.0
1               Buju Banton        African Pride      2326.0
2          Slightly Stoopid   Runnin' With A Gun      2140.0
3                    Burzum                  War       564.0
4               The Misfits              We Bite       473.0
5               The Misfits           Bloodfeast       461.0
6                   Halford    Nailed To The Gun       316.0
7                      Wizo           Kopfschuss       311.0
8            Fischerspooner        We Need A War       253.0
9  Rage Against The Machine  Street Fighting Man       193.0

Collaborative filtering approach

User-based CF top 10 recommendations and model evaluation

In [32]:
from tools.cf_rec import CFRecommender

rec = CFRecommender()

train_data, test_data = rec.load_split()

user_item_matrix = rec.load_sparse()

rec.load_mapping()

model = rec.load_model()

print("CF requirements loaded")

CF requirements loaded

In [36]:
rec.evaluate_model(model, test_data, user_item_matrix, n_users=100)

 Evaluating on 100 test users...
Average Precision@10: 12.10% (100 users)

In [37]:
user_id = 'b7815dbb206eb2831ce0fe040d0aa537e2e800f7'
# user_id = '02a4255f067037ab82375a12d941a3df6ba93248'

song_df = rec.load_data(song_df=True)

rec_df, precision = rec.similar_to_you_listen(
    user_id=user_id,
    song_df=song_df,
    test_data=test_data,
    model=model,
    user_item_matrix=user_item_matrix
)

print(f"precision at 10 for this recommendation: {(precision * 100):.2f} %")
rec_df

precision at 10 for this recommendation: 0.00 %

               artist                                 title  likelihood
0  Eminem / Nate Dogg                      'Till I Collapse    1.090884
1              Eminem                            Without Me    0.974095
2     O'Rosko Raricim                         Terre Promise    0.972845
3              Eminem                   The Real Slim Shady    0.971929
4              Eminem                            My Name Is    0.965362
5   Eminem / Dina Rae                              Superman    0.927559
6         Linkin Park  Bleed It Out [Live At Milton Keynes]    0.877753
7              Eminem                          Just Lose It    0.858924
8         Linkin Park        What I've Done (Album Version)    0.827064
9         Linkin Park            In The End (Album Version)    0.825855

Item-based CF model evaluation

In [38]:
avg_precision = rec.average_precision_at_k_given_track(
    song_id='SOAUWYT12A81C206F1',
    train_data=train_data,
    test_data=test_data,
    song_df=song_df,
    model=model,
    K=10
)

Size of filtered_tracks: 10
Average Precision@10: 12.20%

top 10 recommendations with likelihood

In [40]:
rec_df = rec.get_similar_songs(
    song_id='SOWYSKH12AF72A303A',
    train_data=train_data,
    song_df=song_df,
    model=model
)

user_actual = set(test_data[test_data.user_id == user_id]['song_id'])
precision = rec.calulate_precision(rec_df['song_id'], user_actual, 10)

print(f"precision of this 10 recommendations: {(precision*100):.2f}")
rec_df[['artist', 'title', 'likelihood']]

Size of filtered_tracks: 10
precision of this 10 recommendations: 0.00

            artist                                  title  likelihood
0  matchbox twenty         Could I Be You (Album Version)    0.924119
1  matchbox twenty         You Won't Be Mine (LP Version)    0.921778
2  matchbox twenty                   Soul (Album Version)    0.919711
3  matchbox twenty           Hand Me Down (Album Version)    0.916895
4  matchbox twenty                   Cold (Album Version)    0.915038
5  matchbox twenty         The Difference (Album Version)    0.913536
6  matchbox twenty                 Rest Stop (LP Version)    0.912836
7  matchbox twenty  I'll Believe You When (Album Version)    0.908274
8  matchbox twenty                  The Burn (LP Version)    0.906088
9  matchbox twenty                    Crutch (LP Version)    0.905991

Bonus Part

Top artists based on total play count

In [2]:
user_id = '02a4255f067037ab82375a12d941a3df6ba93248'

df = recommender.your_top_k_songs(user_id)
df

,song_id,artist,title,total_plays
0,SOEGIYH12A6D4FC0E3,Barry Tuckwell/Academy of St Martin-in-the-Fie...,Horn Concerto No. 4 in E flat K495: II. Romanc...,37.0
1,SOJOJUN12A8AE47E1D,Edwyn Collins,Superstar Talking Blues,34.0
2,SONYKOW12AB01849C9,OneRepublic,Secrets,34.0
3,SOPTLQL12AB018D56F,Travie McCoy,Billionaire [feat. Bruno Mars] (Explicit Albu...,32.0
4,SODGVGW12AC9075A8D,Justin Bieber,Somebody To Love,32.0

Songs that have similar artist of the most played song and not listened yet

In [5]:
df = recommender.top_songs_from_favorite_artist(user_id)
df

              song_id         artist                 title     score
0  SODGVGW12AC9075A8D  Justin Bieber      Somebody To Love  110757.0
1  SOGCWUH12AC90732B0  Justin Bieber               U Smile   61568.0
2  SOUGCDK12AC95F075F  Justin Bieber      Never Let You Go   54149.0
3  SODOWUC12AC9097E76  Justin Bieber              One Time   51106.0
4  SOGWJEY12AC9618862  Justin Bieber               Love Me   50925.0
5  SOIDDNJ12AC9071B90  Justin Bieber     That Should Be Me   49119.0
6  SOWCBKV12AC90732A6  Justin Bieber  One Less Lonely Girl   39778.0
7  SOTASGN12AC9075A8F  Justin Bieber   Stuck In The Moment   34671.0
8  SOFKFXC12AC90732A5  Justin Bieber         Down To Earth   31672.0
9  SOJUXGA12AC961885C  Justin Bieber                    Up   21714.0

Top songs of same genre based on the most played genre

In [2]:
user_id = '02a4255f067037ab82375a12d941a3df6ba93248'
df = recommender.song_genre_based(user_id)
df

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,song_id,artist,title,genre,popularity
0,SOIPYPB12A8C1360D4,Evanescence,My Immortal (Album Version),Rock,55655.0
1,SONQEYS12AF72AABC9,Counting Crows,Mr. Jones,Rock,51287.0
2,SODCNEE12A6310E037,David Bowie,Sorrow (1997 Digital Remaster),Rock,47785.0
3,SOGLWGG12A6D4F8046,Pandora's Box,The Want Ad,Rock,42819.0
4,SOHFGKG12A6701C429,Sheryl Crow,Picture,Rock,42563.0